---
aws_frederick:
  public_hosted_zone: files.mapfrederick.city.
  hosted_zone: files.mapfrederick.city.
  ec2:
   instance_size: t2.medium
   ami_id: amazonLinuxAmiId
   asg_size: 1
  buckets:
    - name: awsfrednextcloudstorage
      access_control: Private
  rds:
   - name: "database"
     engine: "mariadb"
     username: "awsfred"
     password: "AQECAHjszbs5uVI7m3fRML/qYWtXh+qnvbk26YIhu4jHW5ZWKQAAAHwwegYJKoZIhvcNAQcGoG0wawIBADBmBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJz9xTriJTlgTbLAjwIBEIA5eOUDPhUJT286ecPCLGy5fZV+qLI06r8j/Os9tBsi2axzDweE20ThDnIaRqZ7ylDGNShA8MuSjJYv"
     storage: "20"
     db_instance_type: "db.t2.micro"
     multiaz: False
boto:
  aws_access_key_id:
  aws_secret_access_key:
  region_name: us-east-1
global:
  environment_name: aws-frederick
  monitor_stack: false
  print_debug: false
  stack_outputs_directory: stack_outputs
  write_stack_outputs: false
logging:
  cloudtrail_log_prefix: cloudtrail_logs
  elb_log_prefix: elb_logs
  s3_bucket: aws-frederick-logs
nat:
  enable_ntp: false
  instance_type: t2.micro
network:
  az_count: 3
  network_cidr_base: 10.0.0.0
  network_cidr_size: '16'
  subnet_config:
  - name: public
    size: '18'
    type: public
  - name: private
    size: '22'
    type: private
  subnet_types:
  - public
  - private
template:
  ami_map_file: ami_cache.json
  description: AWS Frederick Env
  ec2_key_default: aws-frederick
  include_dateGenerated_output: true
  include_templateValidationHash_output: true
  include_timestamp: true
  s3_bucket: aws-frederick-templates
  s3_prefix: templates
  s3_upload: true
  s3_upload_acl: public-read
  timeout_in_minutes: '60'
