---
aws_frederick:
  public_hosted_zone: mapfrederick.city.
  hosted_zone: mapfrederick.city.
  ec2:
    instance_size: t2.small
    ami_id: amazonLinuxAmiId
    asg_size: 1
  buckets:
    - name: www.mapfrederick.city
      static_site: true
      route53: false
      access_control: PublicRead
      cloudfront: true
    - name: files.mapfrederick.city
      static_site: true
      route53: true
      access_control: PublicRead
    - name: maint.mapfrederick.city
      static_site: true
      route53: true
      access_control: PublicRead
      cloudfront: true
  rds:
    - name: "database"
      engine: "postgres"
      username: "awsfred"
      password: "AQEDAHjszbs5uVI7m3fRML/qYWtXh+qnvbk26YIhu4jHW5ZWKQAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDTE+oRHWJKifyQioAIBEIA72gvETU8aFiS3EavIVxuZEVel9JRQzw6WjPl4niL799qJBsFOBZkZQGo1K7gfIeywv33LieubvfjKUpY="
      storage: "15"
      db_instance_type: "db.t2.micro"
      multiaz: False
boto:
  aws_access_key_id:
  aws_secret_access_key:
  region_name: us-east-1
global:
  environment_name: aws-frederick
  monitor_stack: false
  print_debug: false
  stack_outputs_directory: stack_outputs
  write_stack_outputs: false
logging:
  cloudtrail_log_prefix: cloudtrail_logs
  elb_log_prefix: elb_logs
  s3_bucket: aws-frederick-logs
nat:
  enable_ntp: false
  instance_type: t2.micro
network:
  az_count: 3
  network_cidr_base: 10.0.0.0
  network_cidr_size: '16'
  subnet_config:
  - name: public
    size: '18'
    type: public
  - name: private
    size: '22'
    type: private
  subnet_types:
  - public
  - private
template:
  ami_map_file: ami_cache.json
  description: AWS Frederick Env
  ec2_key_default: aws-frederick
  include_dateGenerated_output: true
  include_templateValidationHash_output: true
  include_timestamp: true
  s3_bucket: aws-frederick-templates
  s3_prefix: templates
  s3_upload: true
  s3_upload_acl: public-read
  timeout_in_minutes: '60'
